grpc:
  port: 50051
  timeout: 30s

postgres:
  host: localhost
  port: 5432
  user: your_user
  password: your_password
  dbname: your_dbname
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0